/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ngx-croppie.component';
const styles_NgxCroppieComponent:any[] = ([] as any[]);
export const RenderType_NgxCroppieComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_NgxCroppieComponent,data:{}});
export function View_NgxCroppieComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{imageEdit:0}),(_l()(),i0.ɵeld(0,[[1,0],['imageEdit',
      1]],(null as any),0,'div',([] as any[]),(null as any),[[(null as any),'update']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.NgxCroppieComponent = _v.component;
        if (('update' === en)) {
          const pd_0:any = ((<any>_co.newResult()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any)))],(null as any),(null as any));
}
export function View_NgxCroppieComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ngx-croppie',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgxCroppieComponent_0,
      RenderType_NgxCroppieComponent)),i0.ɵdid(114688,(null as any),0,i1.NgxCroppieComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NgxCroppieComponentNgFactory:i0.ComponentFactory<i1.NgxCroppieComponent> = i0.ɵccf('ngx-croppie',
    i1.NgxCroppieComponent,View_NgxCroppieComponent_Host_0,{croppieOptions:'croppieOptions',
        imageUrl:'imageUrl',bind:'bind',outputFormatOptions:'outputFormatOptions'},
    {result:'result'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvZGVlai9Eb2N1bWVudHMvR2l0SHViL25neC1jcm9wcGllL3NyYy9uZ3gtY3JvcHBpZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvZGVlai9Eb2N1bWVudHMvR2l0SHViL25neC1jcm9wcGllL3NyYy9uZ3gtY3JvcHBpZS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9kZWVqL0RvY3VtZW50cy9HaXRIdWIvbmd4LWNyb3BwaWUvc3JjL25neC1jcm9wcGllLmNvbXBvbmVudC50cy5OZ3hDcm9wcGllQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9kZWVqL0RvY3VtZW50cy9HaXRIdWIvbmd4LWNyb3BwaWUvc3JjL25neC1jcm9wcGllLmNvbXBvbmVudC50cy5OZ3hDcm9wcGllQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiAjaW1hZ2VFZGl0ICh1cGRhdGUpPVwibmV3UmVzdWx0KClcIj48L2Rpdj4iLCI8bmd4LWNyb3BwaWU+PC9uZ3gtY3JvcHBpZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozt1RENBQTtNQUFBO01BQUE7UUFBQTtRQUFBO1FBQWdCO1VBQUE7VUFBQTtRQUFBO1FBQWhCO01BQUE7OztvQkNBQTtNQUFBO29DQUFBLFVBQUE7TUFBQTtJQUFBOzs7Ozs7In0=
