/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ngx-croppie';
import * as i2 from '@angular/common';
export const NgxCroppieModuleNgFactory:i0.NgModuleFactory<i1.NgxCroppieModule> = i0.ɵcmf(i1.NgxCroppieModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.NgxCroppieModule,i1.NgxCroppieModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvZGFuLmpvcmRhbi9Eb2N1bWVudHMvcHJvamVjdHMvbmd4LWNyb3BwaWUvc3JjL25neC1jcm9wcGllLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2Rhbi5qb3JkYW4vRG9jdW1lbnRzL3Byb2plY3RzL25neC1jcm9wcGllL3NyYy9uZ3gtY3JvcHBpZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
